import { OrbitPage, QueryError } from "@/components/OrbitPage";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { FileArchive, FileAudio, FileImage, FileText, Loader2, UploadCloud } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

function iconFor(mime: string) { if (mime.startsWith("image/")) return FileImage; if (mime.startsWith("audio/")) return FileAudio; if (mime.includes("json") || mime.includes("csv")) return FileArchive; return FileText; }
export default function Files() {
  const utils = trpc.useUtils(); const inputRef = useRef<HTMLInputElement>(null); const [busy, setBusy] = useState(false); const { data: files, isLoading, error, refetch } = trpc.files.list.useQuery();
  const upload = trpc.files.upload.useMutation({ onSuccess: () => { utils.files.list.invalidate(); toast.success("Файл добавлен в рабочую область."); }, onError: (error) => toast.error(error.message) });
  const pick = async (file?: File) => { if (!file) return; if (file.size > 16 * 1024 * 1024) return toast.error("Файл должен быть не больше 16 МБ."); setBusy(true); try { const base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); await upload.mutateAsync({ name: file.name, mimeType: file.type || "application/octet-stream", base64 }); } finally { setBusy(false); if (inputRef.current) inputRef.current.value = ""; } };
  return <OrbitPage eyebrow="Безопасные материалы" title="Файлы" action={<><input ref={inputRef} type="file" className="hidden" accept="image/*,audio/*,video/*,.pdf,.txt,.md,.json,.csv" onChange={(e) => pick(e.target.files?.[0])} /><Button onClick={() => inputRef.current?.click()} disabled={busy} className="orbit-button bg-violet-500 hover:bg-violet-400">{busy ? <Loader2 className="mr-2 size-4 animate-spin" /> : <UploadCloud className="mr-2 size-4" />}Загрузить файл</Button></>}>
    <div className="rounded-2xl border border-white/[0.08] bg-[#10182a]"><div className="border-b border-white/[0.07] p-5"><h2 className="font-medium">Рабочая область файлов</h2><p className="mt-1 text-sm text-slate-400">Поддерживаются изображения, аудио, PDF, текст, JSON и CSV до 16 МБ. Файл можно прикрепить к сообщению из чата.</p></div><div className="divide-y divide-white/[0.06]">{error ? <div className="p-5"><QueryError message={error.message} onRetry={() => refetch()} /></div> : isLoading ? <div className="p-5"><div className="h-16 animate-pulse rounded-xl bg-white/[0.04]" /></div> : files?.length ? files.map((file) => { const Icon = iconFor(file.mimeType); return <a href={file.url} target="_blank" rel="noreferrer" key={file.id} className="flex items-center gap-4 px-5 py-4 transition-colors hover:bg-white/[0.035]"><span className="flex size-10 items-center justify-center rounded-xl bg-cyan-300/10 text-cyan-200"><Icon className="size-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-white">{file.name}</span><span className="mt-1 block text-xs text-slate-500">{file.mimeType} · {(file.size / 1024).toFixed(1)} КБ</span></span><Badge className="border border-white/[0.08] bg-white/[0.04] text-[10px] text-slate-300">Открыть</Badge></a>; }) : <div className="px-5 py-16 text-center"><UploadCloud className="mx-auto size-7 text-slate-500" /><h3 className="mt-4 font-medium">Здесь пока нет файлов</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-400">Загрузите документ, изображение или аудио, затем добавьте его к сообщению в Chat.</p></div>}</div></div>
  </OrbitPage>;
}
